language: go
go_import_path: github.com/constabulary/importer
go:
  - 1.4.x
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - tip

sudo: false

script: |
  for d in $(go list github.com/constabulary/importer/...); do
    go test -coverprofile=profile.out $d

    if [ -f profile.out ]; then
      cat profile.out >> coverage.txt
      rm profile.out
    fi
  done

after_success:
  - bash <(curl -s https://codecov.io/bash)
