language: go
go_import_path: github.com/constabulary/importer
go:
  - 1.4.x
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - tip

sudo: false

script:
    go test

after_success:
  - bash <(curl -s https://codecov.io/bash)
